# site settings
title: FH-Prof. Dr. Marc Kurz
subtitle: Professor for Mobile Software Systems | University of Applied Sciences Upper Austria
email: marc.kurz@fh-ooe.at
description: Passionate lecturer, curious researcher in the fields of <br />Mobile User Interaction, Ambient Intelligence, Mobile Software Systems.
baseurl: "/" # the subpath of your site, e.g. /blog
url: https://mrckurz.github.io
author:
street_address: Softwarepark 11
city: Hagenberg
state: 
zip_code: 4232
country: Austria
phone: +43 (0)50804-22827

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/mrckurz
  GitLab:
  Google-Plus: 
  Instagram: https://www.instagram.com/mmrrcccc/
  LinkedIn: https://www.linkedin.com/in/marc-kurz-11516772/
  Twitter: https://twitter.com/marckurz
  Facebook: https://www.facebook.com/marcules
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
